MAIN

  DEFINE
    a,b,c VARCHAR(32)

  CLOSE WINDOW SCREEN

  OPEN WINDOW w WITH FORM "buttonedit"
  INPUT BY NAME a,b,c WITHOUT DEFAULTS ATTRIBUTE(UNBUFFERED)
    ON ACTION zoom
      IF INFIELD(b) THEN
        LET b = CURRENT
      ELSE
        LET c = CURRENT
      END IF
  END INPUT

  CLOSE WINDOW w

END MAIN
