/// FOURJS_START_COPYRIGHT(D,2016)
/// Property of Four Js*
/// (c) Copyright Four Js 2016, 2019. All Rights Reserved.
/// * Trademark of Four Js Development Tools Europe Ltd
///   in the United States and elsewhere
/// 
/// This file can be modified by licensees according to the
/// product manual.
/// FOURJS_END_COPYRIGHT

"use strict";

/**
 * @readonly
 * @enum {string};
 */
gbc.constants.widgetEvents = {
  activate: 'g_activate',
  afterLayout: 'g_afterLayout',
  afterLayoutComplete: 'g_afterLayoutComplete',
  afterLayoutFocusRestored: 'g_afterLayoutFocusRestored',
  blur: 'g_blur',
  change: 'g_change',
  click: 'g_click',
  close: 'g_close',
  copy: 'g_copy',
  contextMenu: 'g_contextMenu',
  created: 'g_created',
  disable: 'g_disable',
  displayChanged: "g_displayChanged",
  destroyed: 'g_destroyed',
  doubleClick: 'g_doubleClick',
  enter: 'g_enter',
  esc: 'g_esc',
  focus: 'g_focus',
  focusRestored: 'g_focusRestored',
  frozen: "g_frozen",
  gridInfoChanged: 'g_gridInfoChanged',
  keyDown: 'g_keyDown',
  keyUp: 'g_keyUp',
  keyArrowDown: 'g_keyArrowDown',
  keyArrowLeft: 'g_keyArrowLeft',
  keyArrowRight: 'g_keyArrowRight',
  keyArrowUp: 'g_keyArrowUp',
  keyEnd: 'g_keyEnd',
  keyHome: 'g_keyHome',
  keyPageUp: 'g_keyPageUp',
  keyPageDown: 'g_keyPageDown',
  keySpace: 'g_keySpace',
  layout: 'g_layout',
  layoutApplied: 'g_layoutApplied',
  layoutInformationChanged: 'g_layoutInformationChanged',
  layoutRequest: 'g_layoutRequest',
  logStepDone: 'g_logStepDone',
  logForwardDone: 'g_logForwardDone',
  modalOut: 'g_modalOut',
  modalResize: "g_modalResize",
  mousewheel: 'g_mouseWheel',
  offset: 'g_offset',
  onBeforeUnload: "g_onbeforeunload",
  onBlur: "g_onBlur",
  onUnload: "g_onunload",
  pageSize: 'g_pageSize',
  pageVisibility: 'g_pageVisibility',
  ready: 'g_ready',
  requestFocus: 'g_requestFocus',
  restart: "g_restart",
  rightClick: 'g_rightClick',
  rowAction: 'g_rowAction',
  scroll: 'g_scroll',
  select: 'g_select',
  selectAll: 'g_selectAll',
  space: 'g_space',
  splitter: 'g_splitter',
  splitterStart: 'g_splitterStart',
  splitterEnd: 'g_splitterEnd',
  splitViewChange: 'g_splitViewChange',
  tableColumnAfterLastItemClick: 'g_tableColumnAfterLastItemClick',
  tableDragEnter: 'g_tableDragEnter',
  tableDragEnd: 'g_tableDragEnd',
  tableDragLeave: 'g_tableDragLeave',
  tableDragStart: 'g_tableDragStart',
  tableDrop: 'g_tableDrop',
  tableDragOver: 'g_tableDragOver',
  tableHeaderClick: 'g_tableHeaderClick',
  tableHeaderOrder: 'g_tableHeaderOrder',
  tableLeftFrozen: 'g_tableTableLeftFrozen',
  tableOrderColumn: 'g_tableOrderColumn',
  tableResetToDefault: 'g_tableResetToDefault',
  tableResizeCol: 'g_tableResizeCol',
  tableRightFrozen: 'g_tableTableRightFrozen',
  tableShowHideCol: 'g_tableShowHideCol',
  tableClick: 'g_tableClick',
  themeChange: 'g_themeChange',
  toggleClick: "g_toggleClick",
  touchEnd: "g_touchEnd",
  touchMove: "g_touchMove",
  touchStart: "g_touchStart",
  unfrozen: "g_unfrozen",
  visibilityChange: "g_visibilityChange",
  webcomponentKeyDown: "g_webcomponentKeyDown"
};
