INSERT INTO countries VALUES (1, 'AF', 'Afghanistan', 93);
INSERT INTO countries VALUES (2, 'AL', 'Albania', 355);
INSERT INTO countries VALUES (3, 'DZ', 'Algeria', 213);
INSERT INTO countries VALUES (4, 'AS', 'American Samoa', 1684);
INSERT INTO countries VALUES (5, 'AD', 'Andorra', 376);
INSERT INTO countries VALUES (6, 'AO', 'Angola', 244);
INSERT INTO countries VALUES (7, 'AI', 'Anguilla', 1264);
INSERT INTO countries VALUES (8, 'AQ', 'Antarctica', 0);
INSERT INTO countries VALUES (9, 'AG', 'Antigua And Barbuda', 1268);
INSERT INTO countries VALUES (10, 'AR', 'Argentina', 54);
INSERT INTO countries VALUES (11, 'AM', 'Armenia', 374);
INSERT INTO countries VALUES (12, 'AW', 'Aruba', 297);
INSERT INTO countries VALUES (13, 'AU', 'Australia', 61);
INSERT INTO countries VALUES (14, 'AT', 'Austria', 43);
INSERT INTO countries VALUES (15, 'AZ', 'Azerbaijan', 994);
INSERT INTO countries VALUES (16, 'BS', 'Bahamas The', 1242);
INSERT INTO countries VALUES (17, 'BH', 'Bahrain', 973);
INSERT INTO countries VALUES (18, 'BD', 'Bangladesh', 880);
INSERT INTO countries VALUES (19, 'BB', 'Barbados', 1246);
INSERT INTO countries VALUES (20, 'BY', 'Belarus', 375);
INSERT INTO countries VALUES (21, 'BE', 'Belgium', 32);
INSERT INTO countries VALUES (22, 'BZ', 'Belize', 501);
INSERT INTO countries VALUES (23, 'BJ', 'Benin', 229);
INSERT INTO countries VALUES (24, 'BM', 'Bermuda', 1441);
INSERT INTO countries VALUES (25, 'BT', 'Bhutan', 975);
INSERT INTO countries VALUES (26, 'BO', 'Bolivia', 591);
INSERT INTO countries VALUES (27, 'BA', 'Bosnia and Herzegovina', 387);
INSERT INTO countries VALUES (28, 'BW', 'Botswana', 267);
INSERT INTO countries VALUES (29, 'BV', 'Bouvet Island', 0);
INSERT INTO countries VALUES (30, 'BR', 'Brazil', 55);
INSERT INTO countries VALUES (31, 'IO', 'British Indian Ocean Territory', 246);
INSERT INTO countries VALUES (32, 'BN', 'Brunei', 673);
INSERT INTO countries VALUES (33, 'BG', 'Bulgaria', 359);
INSERT INTO countries VALUES (34, 'BF', 'Burkina Faso', 226);
INSERT INTO countries VALUES (35, 'BI', 'Burundi', 257);
INSERT INTO countries VALUES (36, 'KH', 'Cambodia', 855);
INSERT INTO countries VALUES (37, 'CM', 'Cameroon', 237);
INSERT INTO countries VALUES (38, 'CA', 'Canada', 1);
INSERT INTO countries VALUES (39, 'CV', 'Cape Verde', 238);
INSERT INTO countries VALUES (40, 'KY', 'Cayman Islands', 1345);
INSERT INTO countries VALUES (41, 'CF', 'Central African Republic', 236);
INSERT INTO countries VALUES (42, 'TD', 'Chad', 235);
INSERT INTO countries VALUES (43, 'CL', 'Chile', 56);
INSERT INTO countries VALUES (44, 'CN', 'China', 86);
INSERT INTO countries VALUES (45, 'CX', 'Christmas Island', 61);
INSERT INTO countries VALUES (46, 'CC', 'Cocos (Keeling) Islands', 672);
INSERT INTO countries VALUES (47, 'CO', 'Colombia', 57);
INSERT INTO countries VALUES (48, 'KM', 'Comoros', 269);
INSERT INTO countries VALUES (49, 'CG', 'Republic Of The Congo', 242);
INSERT INTO countries VALUES (50, 'CD', 'Democratic Republic Of The Congo', 242);
INSERT INTO countries VALUES (51, 'CK', 'Cook Islands', 682);
INSERT INTO countries VALUES (52, 'CR', 'Costa Rica', 506);
INSERT INTO countries VALUES (53, 'CI', 'Cote D''Ivoire (Ivory Coast)', 225);
INSERT INTO countries VALUES (54, 'HR', 'Croatia (Hrvatska)', 385);
INSERT INTO countries VALUES (55, 'CU', 'Cuba', 53);
INSERT INTO countries VALUES (56, 'CY', 'Cyprus', 357);
INSERT INTO countries VALUES (57, 'CZ', 'Czech Republic', 420);
INSERT INTO countries VALUES (58, 'DK', 'Denmark', 45);
INSERT INTO countries VALUES (59, 'DJ', 'Djibouti', 253);
INSERT INTO countries VALUES (60, 'DM', 'Dominica', 1767);
INSERT INTO countries VALUES (61, 'DO', 'Dominican Republic', 1809);
INSERT INTO countries VALUES (62, 'TP', 'East Timor', 670);
INSERT INTO countries VALUES (63, 'EC', 'Ecuador', 593);
INSERT INTO countries VALUES (64, 'EG', 'Egypt', 20);
INSERT INTO countries VALUES (65, 'SV', 'El Salvador', 503);
INSERT INTO countries VALUES (66, 'GQ', 'Equatorial Guinea', 240);
INSERT INTO countries VALUES (67, 'ER', 'Eritrea', 291);
INSERT INTO countries VALUES (68, 'EE', 'Estonia', 372);
INSERT INTO countries VALUES (69, 'ET', 'Ethiopia', 251);
INSERT INTO countries VALUES (70, 'XA', 'External Territories of Australia', 61);
INSERT INTO countries VALUES (71, 'FK', 'Falkland Islands', 500);
INSERT INTO countries VALUES (72, 'FO', 'Faroe Islands', 298);
INSERT INTO countries VALUES (73, 'FJ', 'Fiji Islands', 679);
INSERT INTO countries VALUES (74, 'FI', 'Finland', 358);
INSERT INTO countries VALUES (75, 'FR', 'France', 33);
INSERT INTO countries VALUES (76, 'GF', 'French Guiana', 594);
INSERT INTO countries VALUES (77, 'PF', 'French Polynesia', 689);
INSERT INTO countries VALUES (78, 'TF', 'French Southern Territories', 0);
INSERT INTO countries VALUES (79, 'GA', 'Gabon', 241);
INSERT INTO countries VALUES (80, 'GM', 'Gambia The', 220);
INSERT INTO countries VALUES (81, 'GE', 'Georgia', 995);
INSERT INTO countries VALUES (82, 'DE', 'Germany', 49);
INSERT INTO countries VALUES (83, 'GH', 'Ghana', 233);
INSERT INTO countries VALUES (84, 'GI', 'Gibraltar', 350);
INSERT INTO countries VALUES (85, 'GR', 'Greece', 30);
INSERT INTO countries VALUES (86, 'GL', 'Greenland', 299);
INSERT INTO countries VALUES (87, 'GD', 'Grenada', 1473);
INSERT INTO countries VALUES (88, 'GP', 'Guadeloupe', 590);
INSERT INTO countries VALUES (89, 'GU', 'Guam', 1671);
INSERT INTO countries VALUES (90, 'GT', 'Guatemala', 502);
INSERT INTO countries VALUES (91, 'XU', 'Guernsey and Alderney', 44);
INSERT INTO countries VALUES (92, 'GN', 'Guinea', 224);
INSERT INTO countries VALUES (93, 'GW', 'Guinea-Bissau', 245);
INSERT INTO countries VALUES (94, 'GY', 'Guyana', 592);
INSERT INTO countries VALUES (95, 'HT', 'Haiti', 509);
INSERT INTO countries VALUES (96, 'HM', 'Heard and McDonald Islands', 0);
INSERT INTO countries VALUES (97, 'HN', 'Honduras', 504);
INSERT INTO countries VALUES (98, 'HK', 'Hong Kong S.A.R.', 852);
INSERT INTO countries VALUES (99, 'HU', 'Hungary', 36);
INSERT INTO countries VALUES (100, 'IS', 'Iceland', 354);
INSERT INTO countries VALUES (101, 'IN', 'India', 91);
INSERT INTO countries VALUES (102, 'ID', 'Indonesia', 62);
INSERT INTO countries VALUES (103, 'IR', 'Iran', 98);
INSERT INTO countries VALUES (104, 'IQ', 'Iraq', 964);
INSERT INTO countries VALUES (105, 'IE', 'Ireland', 353);
INSERT INTO countries VALUES (106, 'IL', 'Israel', 972);
INSERT INTO countries VALUES (107, 'IT', 'Italy', 39);
INSERT INTO countries VALUES (108, 'JM', 'Jamaica', 1876);
INSERT INTO countries VALUES (109, 'JP', 'Japan', 81);
INSERT INTO countries VALUES (110, 'XJ', 'Jersey', 44);
INSERT INTO countries VALUES (111, 'JO', 'Jordan', 962);
INSERT INTO countries VALUES (112, 'KZ', 'Kazakhstan', 7);
INSERT INTO countries VALUES (113, 'KE', 'Kenya', 254);
INSERT INTO countries VALUES (114, 'KI', 'Kiribati', 686);
INSERT INTO countries VALUES (115, 'KP', 'Korea North', 850);
INSERT INTO countries VALUES (116, 'KR', 'Korea South', 82);
INSERT INTO countries VALUES (117, 'KW', 'Kuwait', 965);
INSERT INTO countries VALUES (118, 'KG', 'Kyrgyzstan', 996);
INSERT INTO countries VALUES (119, 'LA', 'Laos', 856);
INSERT INTO countries VALUES (120, 'LV', 'Latvia', 371);
INSERT INTO countries VALUES (121, 'LB', 'Lebanon', 961);
INSERT INTO countries VALUES (122, 'LS', 'Lesotho', 266);
INSERT INTO countries VALUES (123, 'LR', 'Liberia', 231);
INSERT INTO countries VALUES (124, 'LY', 'Libya', 218);
INSERT INTO countries VALUES (125, 'LI', 'Liechtenstein', 423);
INSERT INTO countries VALUES (126, 'LT', 'Lithuania', 370);
INSERT INTO countries VALUES (127, 'LU', 'Luxembourg', 352);
INSERT INTO countries VALUES (128, 'MO', 'Macau S.A.R.', 853);
INSERT INTO countries VALUES (129, 'MK', 'Macedonia', 389);
INSERT INTO countries VALUES (130, 'MG', 'Madagascar', 261);
INSERT INTO countries VALUES (131, 'MW', 'Malawi', 265);
INSERT INTO countries VALUES (132, 'MY', 'Malaysia', 60);
INSERT INTO countries VALUES (133, 'MV', 'Maldives', 960);
INSERT INTO countries VALUES (134, 'ML', 'Mali', 223);
INSERT INTO countries VALUES (135, 'MT', 'Malta', 356);
INSERT INTO countries VALUES (136, 'XM', 'Man (Isle of)', 44);
INSERT INTO countries VALUES (137, 'MH', 'Marshall Islands', 692);
INSERT INTO countries VALUES (138, 'MQ', 'Martinique', 596);
INSERT INTO countries VALUES (139, 'MR', 'Mauritania', 222);
INSERT INTO countries VALUES (140, 'MU', 'Mauritius', 230);
INSERT INTO countries VALUES (141, 'YT', 'Mayotte', 269);
INSERT INTO countries VALUES (142, 'MX', 'Mexico', 52);
INSERT INTO countries VALUES (143, 'FM', 'Micronesia', 691);
INSERT INTO countries VALUES (144, 'MD', 'Moldova', 373);
INSERT INTO countries VALUES (145, 'MC', 'Monaco', 377);
INSERT INTO countries VALUES (146, 'MN', 'Mongolia', 976);
INSERT INTO countries VALUES (147, 'MS', 'Montserrat', 1664);
INSERT INTO countries VALUES (148, 'MA', 'Morocco', 212);
INSERT INTO countries VALUES (149, 'MZ', 'Mozambique', 258);
INSERT INTO countries VALUES (150, 'MM', 'Myanmar', 95);
INSERT INTO countries VALUES (151, 'NA', 'Namibia', 264);
INSERT INTO countries VALUES (152, 'NR', 'Nauru', 674);
INSERT INTO countries VALUES (153, 'NP', 'Nepal', 977);
INSERT INTO countries VALUES (154, 'AN', 'Netherlands Antilles', 599);
INSERT INTO countries VALUES (155, 'NL', 'Netherlands The', 31);
INSERT INTO countries VALUES (156, 'NC', 'New Caledonia', 687);
INSERT INTO countries VALUES (157, 'NZ', 'New Zealand', 64);
INSERT INTO countries VALUES (158, 'NI', 'Nicaragua', 505);
INSERT INTO countries VALUES (159, 'NE', 'Niger', 227);
INSERT INTO countries VALUES (160, 'NG', 'Nigeria', 234);
INSERT INTO countries VALUES (161, 'NU', 'Niue', 683);
INSERT INTO countries VALUES (162, 'NF', 'Norfolk Island', 672);
INSERT INTO countries VALUES (163, 'MP', 'Northern Mariana Islands', 1670);
INSERT INTO countries VALUES (164, 'NO', 'Norway', 47);
INSERT INTO countries VALUES (165, 'OM', 'Oman', 968);
INSERT INTO countries VALUES (166, 'PK', 'Pakistan', 92);
INSERT INTO countries VALUES (167, 'PW', 'Palau', 680);
INSERT INTO countries VALUES (168, 'PS', 'Palestinian Territory Occupied', 970);
INSERT INTO countries VALUES (169, 'PA', 'Panama', 507);
INSERT INTO countries VALUES (170, 'PG', 'Papua new Guinea', 675);
INSERT INTO countries VALUES (171, 'PY', 'Paraguay', 595);
INSERT INTO countries VALUES (172, 'PE', 'Peru', 51);
INSERT INTO countries VALUES (173, 'PH', 'Philippines', 63);
INSERT INTO countries VALUES (174, 'PN', 'Pitcairn Island', 0);
INSERT INTO countries VALUES (175, 'PL', 'Poland', 48);
INSERT INTO countries VALUES (176, 'PT', 'Portugal', 351);
INSERT INTO countries VALUES (177, 'PR', 'Puerto Rico', 1787);
INSERT INTO countries VALUES (178, 'QA', 'Qatar', 974);
INSERT INTO countries VALUES (179, 'RE', 'Reunion', 262);
INSERT INTO countries VALUES (180, 'RO', 'Romania', 40);
INSERT INTO countries VALUES (181, 'RU', 'Russia', 70);
INSERT INTO countries VALUES (182, 'RW', 'Rwanda', 250);
INSERT INTO countries VALUES (183, 'SH', 'Saint Helena', 290);
INSERT INTO countries VALUES (184, 'KN', 'Saint Kitts And Nevis', 1869);
INSERT INTO countries VALUES (185, 'LC', 'Saint Lucia', 1758);
INSERT INTO countries VALUES (186, 'PM', 'Saint Pierre and Miquelon', 508);
INSERT INTO countries VALUES (187, 'VC', 'Saint Vincent And The Grenadines', 1784);
INSERT INTO countries VALUES (188, 'WS', 'Samoa', 684);
INSERT INTO countries VALUES (189, 'SM', 'San Marino', 378);
INSERT INTO countries VALUES (190, 'ST', 'Sao Tome and Principe', 239);
INSERT INTO countries VALUES (191, 'SA', 'Saudi Arabia', 966);
INSERT INTO countries VALUES (192, 'SN', 'Senegal', 221);
INSERT INTO countries VALUES (193, 'RS', 'Serbia', 381);
INSERT INTO countries VALUES (194, 'SC', 'Seychelles', 248);
INSERT INTO countries VALUES (195, 'SL', 'Sierra Leone', 232);
INSERT INTO countries VALUES (196, 'SG', 'Singapore', 65);
INSERT INTO countries VALUES (197, 'SK', 'Slovakia', 421);
INSERT INTO countries VALUES (198, 'SI', 'Slovenia', 386);
INSERT INTO countries VALUES (199, 'XG', 'Smaller Territories of the UK', 44);
INSERT INTO countries VALUES (200, 'SB', 'Solomon Islands', 677);
INSERT INTO countries VALUES (201, 'SO', 'Somalia', 252);
INSERT INTO countries VALUES (202, 'ZA', 'South Africa', 27);
INSERT INTO countries VALUES (203, 'GS', 'South Georgia', 0);
INSERT INTO countries VALUES (204, 'SS', 'South Sudan', 211);
INSERT INTO countries VALUES (205, 'ES', 'Spain', 34);
INSERT INTO countries VALUES (206, 'LK', 'Sri Lanka', 94);
INSERT INTO countries VALUES (207, 'SD', 'Sudan', 249);
INSERT INTO countries VALUES (208, 'SR', 'Suriname', 597);
INSERT INTO countries VALUES (209, 'SJ', 'Svalbard And Jan Mayen Islands', 47);
INSERT INTO countries VALUES (210, 'SZ', 'Swaziland', 268);
INSERT INTO countries VALUES (211, 'SE', 'Sweden', 46);
INSERT INTO countries VALUES (212, 'CH', 'Switzerland', 41);
INSERT INTO countries VALUES (213, 'SY', 'Syria', 963);
INSERT INTO countries VALUES (214, 'TW', 'Taiwan', 886);
INSERT INTO countries VALUES (215, 'TJ', 'Tajikistan', 992);
INSERT INTO countries VALUES (216, 'TZ', 'Tanzania', 255);
INSERT INTO countries VALUES (217, 'TH', 'Thailand', 66);
INSERT INTO countries VALUES (218, 'TG', 'Togo', 228);
INSERT INTO countries VALUES (219, 'TK', 'Tokelau', 690);
INSERT INTO countries VALUES (220, 'TO', 'Tonga', 676);
INSERT INTO countries VALUES (221, 'TT', 'Trinidad And Tobago', 1868);
INSERT INTO countries VALUES (222, 'TN', 'Tunisia', 216);
INSERT INTO countries VALUES (223, 'TR', 'Turkey', 90);
INSERT INTO countries VALUES (224, 'TM', 'Turkmenistan', 7370);
INSERT INTO countries VALUES (225, 'TC', 'Turks And Caicos Islands', 1649);
INSERT INTO countries VALUES (226, 'TV', 'Tuvalu', 688);
INSERT INTO countries VALUES (227, 'UG', 'Uganda', 256);
INSERT INTO countries VALUES (228, 'UA', 'Ukraine', 380);
INSERT INTO countries VALUES (229, 'AE', 'United Arab Emirates', 971);
INSERT INTO countries VALUES (230, 'GB', 'United Kingdom', 44);
INSERT INTO countries VALUES (231, 'US', 'United States', 1);
INSERT INTO countries VALUES (232, 'UM', 'United States Minor Outlying Islands', 1);
INSERT INTO countries VALUES (233, 'UY', 'Uruguay', 598);
INSERT INTO countries VALUES (234, 'UZ', 'Uzbekistan', 998);
INSERT INTO countries VALUES (235, 'VU', 'Vanuatu', 678);
INSERT INTO countries VALUES (236, 'VA', 'Vatican City State (Holy See)', 39);
INSERT INTO countries VALUES (237, 'VE', 'Venezuela', 58);
INSERT INTO countries VALUES (238, 'VN', 'Vietnam', 84);
INSERT INTO countries VALUES (239, 'VG', 'Virgin Islands (British)', 1284);
INSERT INTO countries VALUES (240, 'VI', 'Virgin Islands (US)', 1340);
INSERT INTO countries VALUES (241, 'WF', 'Wallis And Futuna Islands', 681);
INSERT INTO countries VALUES (242, 'EH', 'Western Sahara', 212);
INSERT INTO countries VALUES (243, 'YE', 'Yemen', 967);
INSERT INTO countries VALUES (244, 'YU', 'Yugoslavia', 38);
INSERT INTO countries VALUES (245, 'ZM', 'Zambia', 260);
INSERT INTO countries VALUES (246, 'ZW', 'Zimbabwe', 263);
